export const cookiesData = [
    {
        id: 1,
        name: "Clásica",
        description: "New York cookie de vainilla, con chunks de chocolate blanco y negro",
        weight: "120gr",
        price: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsqETptgZVAjMRbRUh52oBR9e85A8zB8pkgg&s",
    },
    {
        id: 2,
        name: "Red Velvet",
        description: "New York cookie de Red Velvet con chunks de chocolate blanco y relleno de queso crema",
        weight: "120gr",
        price: 3,
        image: "https://cookiegood.com/cdn/shop/products/GF_Red_Velvet.jpg?v=1454204420",
    },
    {
        id: 3,
        name: "Brownie",
        description: "New York cookie de brownie, con chunks de chocolate negro y relleno de Nutella",
        weight: "120gr",
        price: 3,
        image: "https://www.shutterstock.com/image-photo/brownie-rounded-cookie-top-view-600nw-2620518985.jpg",
    },
    {
        id: 4,
        name: "Maní",
        description: "New York cookie de vainilla, con chunks de chocolate de leche y relleno de mantequilla de maní",
        weight: "120gr",
        price: 3,
        image: "https://png.pngtree.com/png-vector/20240926/ourlarge/pngtree-delicious-peanut-butter-creamy-spread-in-a-glass-png-image_13911603.png",
    },
    {
        id: 5,
        name: "S'mores",
        description: "New York cookie de vainilla, con chunks de chocolate negro y relleno de malvaviscos",
        weight: "120gr",
        price: 3,
        image: "https://mamascookies.ca/cdn/shop/files/smorescookie_503x503.png?v=1702353000",
    },
    {
        id: 6,
        name: "Nucita",
        description: "New York cookie de brownie y vanilla, con chunks de chocolate blanco y negro, rellena de Nucita",
        weight: "120gr",
        price: 3,       
        image: "https://212global.com/wp-content/uploads/2025/06/611ac90f5066680b8fa00530_thumbnail.png",
    },
    {
        id: 7,
        name: "Samba",
        description: "New York cookie de chocolate rellena de chocolate de fresa, con trozos y topping de Samba",
        weight: "120gr",
        price: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZkQ0Pf_Hv0XnYPl8pG9AZHc6Khu3fcyKo2g&s",
    },
    {
        id: 8,
        name: "Churro",
        description: "New York cookie de churro con canela y azúcar, rellena con dulce de leche (arequipe)",
        weight: "120gr",
        price: 3,       
        image: "https://png.pngtree.com/png-clipart/20240103/original/pngtree-churros-illustration-png-image_14008389.png",
    },
    {
        id: 9,
        name: "Monster",
        description: "New York cookie de vainilla, con pedazos de oreo y relleno de chocolate blanco",
        weight: "120gr",
        price: 3,
        image: "https://i.pinimg.com/736x/e8/1b/75/e81b75ae64f4718be13b5f7664683c8e.jpg",
    },
    {
        id: 10,
        name: "Funfetti",
        description: "New York cookie de vainilla cubierta de chispas de colores y relleno de chocolate blanco",
        weight: "120gr",
        price: 3,
        image: "https://png.pngtree.com/png-clipart/20241129/original/pngtree-funfetti-cake-png-image_17407874.png",
    },
];